[package]
name = "sal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
phf = { version = "0.8", features = ["macros"] }

[dev-dependencies]
proptest = "1.0.0"
