brace_style = "AlwaysNextLine"
comment_width = 120
edition = "2018"
max_width = 120
unstable_features = true
match_block_trailing_comma = true
trailing_comma = "Never"
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"