[package]
name = "shaderc"
version = "0.1.0"
authors = ["Yuri Edward <yuri6037@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
regex = "1.4.5"
rglslang = { path = "../rglslang" }
crossbeam-channel = "0.5.1"
sal = { path = "../sal" }
phf = { version = "0.8", features = ["macros"] }
bpx = { version = "3.2.0", path = "../../bpx-rs", features = ["package", "shader"] }
log = "0.4.14"
simple_logger = "1.13.0"
