[package]
name = "shaderd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpx = { version = "4.0.0-beta-5", features = ["package", "shader", "serde", "sd-formatting"] }
clap = "3.1.0"
